# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 385)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_13 = QtWidgets.QWidget(self.centralwidget)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.time_label = QtWidgets.QLabel(self.groupBox)
        self.time_label.setObjectName("time_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.time_label)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.solar_elevation_label = QtWidgets.QLabel(self.groupBox)
        self.solar_elevation_label.setObjectName("solar_elevation_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.solar_elevation_label)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.solar_azimuth_label = QtWidgets.QLabel(self.groupBox)
        self.solar_azimuth_label.setObjectName("solar_azimuth_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.solar_azimuth_label)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.latitude_label = QtWidgets.QLabel(self.groupBox)
        self.latitude_label.setObjectName("latitude_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.latitude_label)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.longitude_label = QtWidgets.QLabel(self.groupBox)
        self.longitude_label.setObjectName("longitude_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.longitude_label)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_11.addWidget(self.groupBox)
        self.groupBox_13 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_13)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.compass_label = QtWidgets.QLabel(self.groupBox_13)
        self.compass_label.setObjectName("compass_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.compass_label)
        self.label_19 = QtWidgets.QLabel(self.groupBox_13)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.distance_traveled_label = QtWidgets.QLabel(self.groupBox_13)
        self.distance_traveled_label.setObjectName("distance_traveled_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.distance_traveled_label)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_11.addWidget(self.groupBox_13)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget_13)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.check_cameras_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.check_cameras_btn.setObjectName("check_cameras_btn")
        self.verticalLayout_7.addWidget(self.check_cameras_btn)
        self.focus_cameras_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.focus_cameras_btn.setObjectName("focus_cameras_btn")
        self.verticalLayout_7.addWidget(self.focus_cameras_btn)
        self.horizontalLayout_11.addWidget(self.groupBox_4)
        self.verticalLayout_8.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.centralwidget)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.groupBox1 = QtWidgets.QGroupBox(self.widget_14)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_9 = QtWidgets.QWidget(self.groupBox1)
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.widget_9)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.photos_taken_1 = QtWidgets.QLabel(self.widget_9)
        self.photos_taken_1.setObjectName("photos_taken_1")
        self.horizontalLayout_7.addWidget(self.photos_taken_1)
        self.verticalLayout_4.addWidget(self.widget_9)
        self.enable_camera_1_btn = QtWidgets.QPushButton(self.groupBox1)
        self.enable_camera_1_btn.setCheckable(True)
        self.enable_camera_1_btn.setChecked(False)
        self.enable_camera_1_btn.setObjectName("enable_camera_1_btn")
        self.verticalLayout_4.addWidget(self.enable_camera_1_btn)
        self.transfer_photos_1_btn = QtWidgets.QPushButton(self.groupBox1)
        self.transfer_photos_1_btn.setObjectName("transfer_photos_1_btn")
        self.verticalLayout_4.addWidget(self.transfer_photos_1_btn)
        self.reset_1_btn = QtWidgets.QPushButton(self.groupBox1)
        self.reset_1_btn.setObjectName("reset_1_btn")
        self.verticalLayout_4.addWidget(self.reset_1_btn)
        self.horizontalLayout_12.addWidget(self.groupBox1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_14)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_10 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_15 = QtWidgets.QLabel(self.widget_10)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_8.addWidget(self.label_15)
        self.photos_taken_2 = QtWidgets.QLabel(self.widget_10)
        self.photos_taken_2.setObjectName("photos_taken_2")
        self.horizontalLayout_8.addWidget(self.photos_taken_2)
        self.verticalLayout_5.addWidget(self.widget_10)
        self.enable_camera_2_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.enable_camera_2_btn.setCheckable(True)
        self.enable_camera_2_btn.setChecked(False)
        self.enable_camera_2_btn.setObjectName("enable_camera_2_btn")
        self.verticalLayout_5.addWidget(self.enable_camera_2_btn)
        self.transfer_photos_2_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.transfer_photos_2_btn.setObjectName("transfer_photos_2_btn")
        self.verticalLayout_5.addWidget(self.transfer_photos_2_btn)
        self.reset_2_btn = QtWidgets.QPushButton(self.groupBox_2)
        self.reset_2_btn.setObjectName("reset_2_btn")
        self.verticalLayout_5.addWidget(self.reset_2_btn)
        self.horizontalLayout_12.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_14)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_11 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_11.setObjectName("widget_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_17 = QtWidgets.QLabel(self.widget_11)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.photos_taken_3 = QtWidgets.QLabel(self.widget_11)
        self.photos_taken_3.setObjectName("photos_taken_3")
        self.horizontalLayout_9.addWidget(self.photos_taken_3)
        self.verticalLayout_6.addWidget(self.widget_11)
        self.enable_camera_3_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.enable_camera_3_btn.setCheckable(True)
        self.enable_camera_3_btn.setChecked(False)
        self.enable_camera_3_btn.setObjectName("enable_camera_3_btn")
        self.verticalLayout_6.addWidget(self.enable_camera_3_btn)
        self.transfer_photos_3_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.transfer_photos_3_btn.setObjectName("transfer_photos_3_btn")
        self.verticalLayout_6.addWidget(self.transfer_photos_3_btn)
        self.reset_3_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.reset_3_btn.setObjectName("reset_3_btn")
        self.verticalLayout_6.addWidget(self.reset_3_btn)
        self.horizontalLayout_12.addWidget(self.groupBox_3)
        self.verticalLayout_8.addWidget(self.widget_14)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_8.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Time and Location"))
        self.label_5.setText(_translate("MainWindow", "Time:"))
        self.time_label.setText(_translate("MainWindow", "12:00:00 PM"))
        self.label_9.setText(_translate("MainWindow", "Solar Elevation:"))
        self.solar_elevation_label.setText(_translate("MainWindow", "90°"))
        self.label_7.setText(_translate("MainWindow", "Solar Azimuth:"))
        self.solar_azimuth_label.setText(_translate("MainWindow", "0°"))
        self.label.setText(_translate("MainWindow", "Latitude:"))
        self.latitude_label.setText(_translate("MainWindow", "0.000000"))
        self.label_3.setText(_translate("MainWindow", "Longitude:"))
        self.longitude_label.setText(_translate("MainWindow", "0.000000"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Cart Info"))
        self.label_11.setText(_translate("MainWindow", "Compass:"))
        self.compass_label.setText(_translate("MainWindow", "0°"))
        self.label_19.setText(_translate("MainWindow", "Distance Traveled"))
        self.distance_traveled_label.setText(_translate("MainWindow", "0 m"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Cart Controls"))
        self.check_cameras_btn.setText(_translate("MainWindow", "Check Cameras"))
        self.focus_cameras_btn.setText(_translate("MainWindow", "Focus Cameras"))
        self.groupBox1.setTitle(_translate("MainWindow", "Left Camera"))
        self.label_13.setText(_translate("MainWindow", "Photos Taken:"))
        self.photos_taken_1.setText(_translate("MainWindow", "0"))
        self.enable_camera_1_btn.setText(_translate("MainWindow", "Enable Camera"))
        self.transfer_photos_1_btn.setText(_translate("MainWindow", "Transfer Photos"))
        self.reset_1_btn.setText(_translate("MainWindow", "Reset"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Center Camera"))
        self.label_15.setText(_translate("MainWindow", "Photos Taken:"))
        self.photos_taken_2.setText(_translate("MainWindow", "0"))
        self.enable_camera_2_btn.setText(_translate("MainWindow", "Enable Camera"))
        self.transfer_photos_2_btn.setText(_translate("MainWindow", "Transfer Photos"))
        self.reset_2_btn.setText(_translate("MainWindow", "Reset"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Right Camera"))
        self.label_17.setText(_translate("MainWindow", "Photos Taken:"))
        self.photos_taken_3.setText(_translate("MainWindow", "0"))
        self.enable_camera_3_btn.setText(_translate("MainWindow", "Enable Camera"))
        self.transfer_photos_3_btn.setText(_translate("MainWindow", "Transfer Photos"))
        self.reset_3_btn.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

